# Generated by Django 3.2.7 on 2021-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('level', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True, default=' the images related to a Doc are retrieved by the images property of doc which is generated from the related_name attribute in the ForeignKey')),
                ('image_url', models.URLField(blank=True)),
                ('hint', models.TextField(blank=True, default='hint')),
                ('answer', models.CharField(blank=True, max_length=400)),
                ('format', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StageTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, default=' the images related to a Doc are retrieved by the images property of doc which is generated from the related_name attribute in the ForeignKey')),
                ('answer', models.CharField(blank=True, max_length=400)),
                ('level', models.IntegerField(unique=True)),
                ('image_url', models.URLField(blank=True)),
                ('format', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
