# Generated by Django 3.2.7 on 2021-10-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagetwo',
            name='audio_url',
            field=models.URLField(blank=True),
        ),
    ]
