# Generated by Django 3.2.7 on 2021-12-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaders',
            old_name='playerNum',
            new_name='cutoffScore',
        ),
    ]
